.TH TomboyTools









.SH NAME
tomboytools \- import and export Tomboy notes, various formats supported.

.SH SYNOPSIS
tomboytools  [\-s SRC_Dir]  [\-d DEST_Dir]  (for GUI mode)

tomboytools  \-a  \-\-action=[note2md; note2txt; md2note; txt2note; note2man] OTHER_OPTIONS (for command line mode)

.SH DESCRIPTION
A tool that can be used to export or import Tomboy notes, for use with tomboy\-ng, Tomboy or possibly, GNote.  Will export notes to mark down (in a subset of commonMark), plain text, HTML (optionally following internal Tomboy note links) or Man Page.

The application will run in command line mode if it is provide sufficent parameters or will open a GUI offering a richer set of options.  Its also possible to go to GUI mode if the command line specifies \-s and/or \-d to define the directory where input files are found, the source, and the directory where output files will be written, the destination.

When exporting to Man Page, you should use the Man Page template or, in tomboy\-ng Single Note Mode, rename the template to your application name. The template has instructions.

.SH OPTIONS
.TP
\-a  \-\-action=[note2md; note2txt; md2note; txt2note, note2man]
Use in command line mode, choose the output format.

.TP
\-s \-\-source=[dir or KEY]
The directory where input files are to be found, useful in both command line and GUI mode. For importing, defaults to current directory.

.TP
\-d  \-\-destination=[dir or KEY]
The directory where output files will be written, useful in both command line and GUI mode. For exporting, defaults to current directory.

.TP
\-b  \-\-notebook="Notebook Name"
The name of a Notebook containing the notes you wish exported. This means tomboy\-ng or Tomboy Notebook (or, possibly, a GNote one).

.TP
\-n  \-\-note="Note Name"
The title of a note you wish to export.

.TP
\-f  \-\-file="File Name"
The file name of a note (without path) you wish to import (or, in the case of note2man, export or convert). The note will be looked for in the source directory, \-s above.

.TP
\-t  \-\-title\-line
Note Title is the first line of the source file. The output file will have the same file name as the input file.

.TP
\-V  \-\-verbose
Tell us what it is doing.

.TP
\-e  \-\-examples
Print some example command lines and exit.

.TP
\-\-help
Print this help and exit.

.SH MAN PAGES
Tomboytools can make a reasonable basic man page from a tomboy\-ng note that was based on a special template (available from TomboyTools Github page, it starts with 903C31...). The template has some basic help text in italics, you can remove it if you like but the conversion ignores italic text.  In most cases you enter text in place of the Italics in pretty much the format a man page is displayed in. There are a number of headings, you can easily add additional ones for free form text.

Its convient to have the note version in your version controlled tree, use tomboy\-ng to edit and maintain it and use TomboyTools to convert it to a .1 file when you are ready. Keep the note as (eg only) my\-app\-man.note, set its title (using tomboy\-ng) to my\-app and TT will make my\-app.1

Error details are embedded in the .1 file, always check !

You may view the tomboytools note and .1 file in https://github.com/davidbannon/TomboyTools/tree/main/package/deb_files

.SH FILES

/usr/bin/tomboytools

tomboytools.1

.SH SEE ALSO
https://github.com/davidbannon/TomboyTools





